# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20160504_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='full_screen',
            field=models.BooleanField(default=False),
        ),
    ]
