# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_full_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='full_screen_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
