# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-01 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_full_screen_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='full_screen',
            new_name='show_full_screen',
        ),
    ]
