# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-15 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_full_screen_datetime'),
        ('notifications', '0006_indexes'),
    ]

    operations = [
    ]
